In [17]:
import pandas as pd
from torchvision.datasets import ImageFolder
import re

data_path = '/ix/akovashka/arr159/imagenet-r' 
dataset = ImageFolder(root=data_path)

# extract relative path
img_ids = ['/'.join(path.split('/')[-2:]) for path, _ in dataset.samples]

# extract attributes
pattern = re.compile(r"([^/]+)_(\d+)\.jpg$")

attributes=[]
for path, _ in dataset.samples:
    match = pattern.search(path)
    if match:
        transformation_type = match.group(1)
    else:
        raise Exception
    attributes.append(transformation_type)
        
ground_truth_classes = [label for _, label in dataset.samples]
gt_codes = [path.split('/')[-2] for path, _ in dataset.samples]

df = pd.DataFrame({
    'img_id': img_ids,
    'attribute': attributes,
    'gt_code': gt_codes,
    'gt': ground_truth_classes
})

In [7]:
df['attribute'].unique()

array(['art', 'cartoon', 'deviantart', 'embroidery', 'graffiti',
       'graphic', 'misc', 'origami', 'painting', 'sculpture', 'sketch',
       'sticker', 'toy', 'videogame', 'tattoo'], dtype=object)

In [14]:
from os import path

mapping_raw = open(path.join(data_path, 'README.txt')).readlines()
mapping = {line.split()[0]: line.split()[1].rstrip() for line in mapping_raw[13:]}

In [19]:
df.to_csv('mock_data/dataset.csv')

In [22]:
import json
with open('mock_data/mapping.json', 'w') as json_file:
    json.dump(mapping, json_file, indent=4)

# Create Pred Splits

In [2]:
import random

def corruption_fn(df, condition_fn, corruption_matrix, corruption_prob):
    predictions = []
    for _, row in df.iterrows():
        if condition_fn(row):
            if random.random() < corruption_prob:
                sampled_class = random.choices(list(range(len(corruption_matrix[row['gt']]))), weights=corruption_matrix[row['gt']], k=1)[0] 
                predictions.append(sampled_class)
            else:
                predictions.append(row['pred'])
        else:
            predictions.append(row['pred']) # keep it the same
    return predictions

In [35]:
import numpy as np
condition = lambda row: True
df['pred'] = df['gt']
corruption_matrix = np.ones((200,200)) # these are the weights for class change
# set diagonal to zero
np.fill_diagonal(corruption_matrix, 0)

predictions = corruption_fn(df, condition, corruption_matrix, corruption_prob=0.25)
with open('mock_data/pred_splits/split_0.txt', 'w') as f:
    for pred in predictions:
        f.write(f'{pred}\n')

In [44]:
condition = lambda row: row['attribute']=='sketch' and mapping[row['gt_code']] == 'goose'
df['pred'] = df['gt']
corruption_matrix = np.ones((200,200)) # these are the weights for class change
# set diagonal to zero
np.fill_diagonal(corruption_matrix, 0)

predictions = corruption_fn(df, condition, corruption_matrix, corruption_prob=0.6)
df['pred'] = predictions

condition = lambda row: not (row['attribute']=='sketch' and mapping[row['gt_code']] == 'goose')
corruption_matrix = np.ones((200,200)) # these are the weights for class change
# set diagonal to zero
np.fill_diagonal(corruption_matrix, 0)

predictions = corruption_fn(df, condition, corruption_matrix, corruption_prob=0.25)

In [45]:
(np.array(predictions) != df['gt'].values).mean()

0.25016666666666665

In [46]:

with open('mock_data/pred_splits/split_1.txt', 'w') as f:
    for pred in predictions:
        f.write(f'{pred}\n')

In [53]:
gt_code2idx = dict(df[['gt_code', 'gt']].drop_duplicates().values)
class_name2idx = {mapping[gt_code]: idx for gt_code, idx in gt_code2idx.items()}

In [54]:
condition = lambda row: row['attribute']=='sketch' and mapping[row['gt_code']] == 'orangutan'
df['pred'] = df['gt']
corruption_matrix = np.ones((200,200)) # these are the weights for class change
# set diagonal to zero
np.fill_diagonal(corruption_matrix, 0)
corruption_matrix[class_name2idx['orangutan']][class_name2idx['chimpanzee']]=50

predictions = corruption_fn(df, condition, corruption_matrix, corruption_prob=0.6)
df['pred'] = predictions

condition2 = lambda row: not condition(row)
corruption_matrix = np.ones((200,200)) # these are the weights for class change
# set diagonal to zero
np.fill_diagonal(corruption_matrix, 0)

predictions = corruption_fn(df, condition2, corruption_matrix, corruption_prob=0.25)

In [55]:
(np.array(predictions) != df['gt'].values).mean()

0.25216666666666665

In [56]:
with open('mock_data/pred_splits/split_2.txt', 'w') as f:
    for pred in predictions:
        f.write(f'{pred}\n')

# Create Demo GT Class-Based Error Slice Splits

In [1]:
import pandas as pd
import numpy as np
import json

with open('mock_data/mapping.json', 'r') as json_file:
    mapping=json.load(json_file)
    
df = pd.read_csv('mock_data/dataset.csv')
df.head()

   Unnamed: 0                img_id attribute    gt_code  gt
0           0   n01443537/art_0.jpg       art  n01443537   0
1           1   n01443537/art_1.jpg       art  n01443537   0
2           2  n01443537/art_10.jpg       art  n01443537   0
3           3  n01443537/art_11.jpg       art  n01443537   0
4           4  n01443537/art_12.jpg       art  n01443537   0

In [9]:
df.describe(include='all')

,Unnamed: 0,img_id,attribute,gt_code,gt
count,30000.000000,30000,30000,30000,30000.000000
unique,NaN,30000,15,200,NaN
top,NaN,n01518878/embroidery_1.jpg,misc,n07734744,NaN
freq,NaN,1,5673,430,NaN
mean,14999.500000,NaN,NaN,NaN,98.845200
std,8660.398374,NaN,NaN,NaN,59.539619
min,0.000000,NaN,NaN,NaN,0.000000
25%,7499.750000,NaN,NaN,NaN,47.000000
50%,14999.500000,NaN,NaN,NaN,97.000000
75%,22499.250000,NaN,NaN,NaN,154.000000
max,29999.000000,NaN,NaN,NaN,199.000000

In [17]:
df[['gt_code', 'attribute']].drop_duplicates()

         gt_code   attribute
0      n01443537         art
13     n01443537     cartoon
55     n01443537  deviantart
72     n01443537  embroidery
84     n01443537    graffiti
...          ...         ...
29768  n10565667         toy
29782  n10565667   videogame
29811  n12267677  deviantart
29839  n12267677        misc
29976  n12267677      sketch

[2068 rows x 2 columns]

In [12]:
condition = lambda row: row['attribute']=='sketch' and mapping[row['gt_code']] == 'goose'
df['pred'] = df['gt']
corruption_matrix = np.ones((200,200)) # these are the weights for class change
# set diagonal to zero
np.fill_diagonal(corruption_matrix, 0)

predictions = corruption_fn(df, condition, corruption_matrix, corruption_prob=1.0)
df['pred'] = predictions

condition = lambda row: not (row['attribute']=='sketch' and mapping[row['gt_code']] == 'goose')
corruption_matrix = np.ones((200,200)) # these are the weights for class change
# set diagonal to zero
np.fill_diagonal(corruption_matrix, 0)

predictions = corruption_fn(df, condition, corruption_matrix, corruption_prob=0.01)
df['pred']=predictions

In [19]:
df[df['pred'] != df['gt']].groupby(['gt']).count()['gt_code'].values

array([ 2,  1,  1,  1,  1,  1,  3,  3,  1,  1,  1,  3,  2,  1,  4,  3,  1,
        2,  1, 24,  1,  2,  1,  1,  6,  1,  2,  2,  1,  5,  1,  2,  2,  1,
        1,  1,  2,  1,  1,  2,  3,  1,  1,  2,  1,  2,  2,  1,  2,  1,  1,
        2,  1,  2,  2,  1,  3,  3,  1,  3,  2,  1,  4,  1,  2,  1,  3,  2,
        1,  1,  1,  2,  1,  1,  2,  4,  3,  2,  3,  3,  1,  2,  2,  2,  2,
        2,  2,  2,  2,  1,  2,  1,  2,  3,  1,  1,  3,  2,  1,  1,  1,  1,
        4,  2,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  1,  2,  1,
        3,  1,  3,  3,  1,  2,  3,  2,  1,  3,  7,  1,  1,  4,  1,  4,  4,
        1,  3,  3,  1,  1,  3,  4,  1,  2,  3,  2,  3,  1,  1,  2,  1,  5,
        5,  2,  3])

In [20]:
with open('mock_data/demo_pred_splits/split_0_goose_sketch.txt', 'w') as f:
    for pred in predictions:
        f.write(f'{pred}\n')

In [12]:
import random, json
import numpy as np
import pandas as pd
from tqdm import tqdm

def corruption_fn(df, condition_fn, corruption_matrix, corruption_prob):
    predictions = []
    for _, row in df.iterrows():
        if condition_fn(row):
            if random.random() < corruption_prob:
                sampled_class = random.choices(list(range(len(corruption_matrix[row['gt']]))), weights=corruption_matrix[row['gt']], k=1)[0] 
                predictions.append(sampled_class)
            else:
                predictions.append(row['pred'])
        else:
            predictions.append(row['pred']) # keep it the same
    return predictions

with open('mock_data/mapping.json', 'r') as json_file:
    mapping=json.load(json_file)
    
df = pd.read_csv('mock_data/dataset.csv')
for _, row in tqdm(df[['gt_code', 'attribute']].drop_duplicates().iterrows()): 
    temp_df = pd.read_csv('mock_data/dataset.csv')
    
    gt_code, attr = row
#     print(row, gt_code, attr)
    condition = lambda row: row['attribute']==attr and row['gt_code']==gt_code
    temp_df['pred'] = temp_df['gt']
    corruption_matrix = np.ones((200,200)) # these are the weights for class change
    # set diagonal to zero
    np.fill_diagonal(corruption_matrix, 0)

    predictions = corruption_fn(temp_df, condition, corruption_matrix, corruption_prob=1.0)
    temp_df['pred'] = predictions

    condition = lambda row: not (row['attribute']==attr and row['gt_code'] == gt_code)
    corruption_matrix = np.ones((200,200)) # these are the weights for class change
    # set diagonal to zero
    np.fill_diagonal(corruption_matrix, 0)

    predictions = corruption_fn(temp_df, condition, corruption_matrix, corruption_prob=0.01)
    temp_df['pred']=predictions
    
    output_file_name = f"mock_data/demo_pred_splits/split_0_{mapping[row['gt_code']]}_{attr}.txt"
    with open(output_file_name, 'w') as f:
        for pred in predictions:
            f.write(f'{pred}\n')
        
#     break

2068it [53:06,  1.54s/it]

In [10]:
temp_df[(temp_df['gt_code']=='n01443537') & (temp_df['attribute']=='art')]

    Unnamed: 0                img_id attribute    gt_code  gt  pred
0            0   n01443537/art_0.jpg       art  n01443537   0     5
1            1   n01443537/art_1.jpg       art  n01443537   0    52
2            2  n01443537/art_10.jpg       art  n01443537   0   196
3            3  n01443537/art_11.jpg       art  n01443537   0    16
4            4  n01443537/art_12.jpg       art  n01443537   0   177
5            5   n01443537/art_2.jpg       art  n01443537   0   103
6            6   n01443537/art_3.jpg       art  n01443537   0   129
7            7   n01443537/art_4.jpg       art  n01443537   0   120
8            8   n01443537/art_5.jpg       art  n01443537   0    88
9            9   n01443537/art_6.jpg       art  n01443537   0   141
10          10   n01443537/art_7.jpg       art  n01443537   0   128
11          11   n01443537/art_8.jpg       art  n01443537   0   105
12          12   n01443537/art_9.jpg       art  n01443537   0   122

In [8]:
df[(df['gt_code']=='n01443537') & (df['attribute']=='art')]

    Unnamed: 0                img_id attribute    gt_code  gt
0            0   n01443537/art_0.jpg       art  n01443537   0
1            1   n01443537/art_1.jpg       art  n01443537   0
2            2  n01443537/art_10.jpg       art  n01443537   0
3            3  n01443537/art_11.jpg       art  n01443537   0
4            4  n01443537/art_12.jpg       art  n01443537   0
5            5   n01443537/art_2.jpg       art  n01443537   0
6            6   n01443537/art_3.jpg       art  n01443537   0
7            7   n01443537/art_4.jpg       art  n01443537   0
8            8   n01443537/art_5.jpg       art  n01443537   0
9            9   n01443537/art_6.jpg       art  n01443537   0
10          10   n01443537/art_7.jpg       art  n01443537   0
11          11   n01443537/art_8.jpg       art  n01443537   0
12          12   n01443537/art_9.jpg       art  n01443537   0